server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: root
    password: 1234
#    driver-class-name: org.postgresql.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect